/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JavaPushMailNotificationSettingsPanel.java
 *
 * Created on Nov 11, 2011, 8:17:58 AM
 */
package com.mofirouz.javapushmail.app.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author mo
 */
public class JavaPushMailNotificationSettingsPanel extends javax.swing.JPanel {

    public static final Vector<String> notificationTextOptions = new Vector<String>();
    public static final Vector<String> durationOptions = new Vector<String>();
    
    private ComboBoxModel titleModel, firstLineModel, secondLineModel, durationModel;
    
    /** Creates new form JavaPushMailNotificationSettingsPanel */
    public JavaPushMailNotificationSettingsPanel() {
        initComponents();
        initModels();
        initListeners();
    }

    private void initModels() {
        notificationTextOptions.add("Account Name");
        notificationTextOptions.add("Subject");
        notificationTextOptions.add("From");
        notificationTextOptions.add("Generic Text");
        
        durationOptions.add("5 seconds");
        durationOptions.add("10 seconds");
        durationOptions.add("30 seconds");
        
        titleModel = new DefaultComboBoxModel(notificationTextOptions);
        firstLineModel = new DefaultComboBoxModel(notificationTextOptions);
        secondLineModel = new DefaultComboBoxModel(notificationTextOptions);
        durationModel = new DefaultComboBoxModel(durationOptions);
        
        titleComboBox.setModel(titleModel);
        firstLineComboBox.setModel(titleModel);
        secondLineComboBox.setModel(titleModel);
        durationComboBox.setModel(durationModel);
    }
    
    private void initListeners() {
        ActionListener themeActionListener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                refreshFallbackThemeRadios();
            }
        };
        
        fallbackNotificationRadioButton.addActionListener(themeActionListener);
        growlRadioButton.addActionListener(themeActionListener);
        nOSDRadioButton.addActionListener(themeActionListener);
    }
    
    private void refreshFallbackThemeRadios() {
        darkThemeRadioBox.setEnabled(fallbackNotificationRadioButton.isSelected());
        lightThemeRadioBox.setEnabled(fallbackNotificationRadioButton.isSelected());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titleComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        firstLineComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        secondLineComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        durationComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fallbackNotificationRadioButton = new javax.swing.JRadioButton();
        growlRadioButton = new javax.swing.JRadioButton();
        nOSDRadioButton = new javax.swing.JRadioButton();
        lightThemeRadioBox = new javax.swing.JRadioButton();
        darkThemeRadioBox = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        shortcutkeyField = new javax.swing.JTextField();
        keyCtrlCheckBox = new javax.swing.JCheckBox();
        keyAltCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        hideButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        saveSettingsButton = new javax.swing.JButton();
        loggingCheckBox = new javax.swing.JCheckBox();

        setMinimumSize(new java.awt.Dimension(612, 352));
        setName("Notification Settings"); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(612, 352));

        jPanel2.setOpaque(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Notification Title:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("First Line:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Second Line:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Duration:");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel8.setText("Notification Text");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 59, Short.MAX_VALUE)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(firstLineComboBox, 0, 170, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(durationComboBox, 0, 170, Short.MAX_VALUE))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(42, 42, 42)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(secondLineComboBox, 0, 170, Short.MAX_VALUE))
                    .add(jLabel8)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(titleComboBox, 0, 170, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8)
                .add(18, 18, 18)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(titleComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jLabel2)
                        .add(13, 13, 13))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(firstLineComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(secondLineComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(durationComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setOpaque(false);

        buttonGroup1.add(fallbackNotificationRadioButton);
        fallbackNotificationRadioButton.setText("Fallback Notification");

        buttonGroup1.add(growlRadioButton);
        growlRadioButton.setSelected(true);
        growlRadioButton.setText("Growl");

        buttonGroup1.add(nOSDRadioButton);
        nOSDRadioButton.setText("NotifyOSD");

        buttonGroup2.add(lightThemeRadioBox);
        lightThemeRadioBox.setSelected(true);
        lightThemeRadioBox.setText("Light Theme");
        lightThemeRadioBox.setEnabled(false);

        buttonGroup2.add(darkThemeRadioBox);
        darkThemeRadioBox.setText("Dark Theme");
        darkThemeRadioBox.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 13));
        jLabel9.setText("Notification Style");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel9)
                    .add(growlRadioButton)
                    .add(nOSDRadioButton)
                    .add(fallbackNotificationRadioButton)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(darkThemeRadioBox)
                            .add(lightThemeRadioBox))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel9)
                .add(18, 18, 18)
                .add(growlRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(nOSDRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(fallbackNotificationRadioButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lightThemeRadioBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(darkThemeRadioBox)
                .add(23, 23, 23))
        );

        jPanel4.setOpaque(false);

        shortcutkeyField.setText("M");

        keyCtrlCheckBox.setSelected(true);
        keyCtrlCheckBox.setText("Ctrl");
        keyCtrlCheckBox.setEnabled(false);

        keyAltCheckBox.setSelected(true);
        keyAltCheckBox.setText("Alt");
        keyAltCheckBox.setEnabled(false);

        jLabel4.setText("+");

        jLabel5.setText("+");

        jLabel6.setText("Keyboard Shortcut (to bring the application up):");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                .add(keyCtrlCheckBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(keyAltCheckBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(shortcutkeyField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(8, 8, 8))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(keyCtrlCheckBox)
                .add(jLabel4)
                .add(keyAltCheckBox)
                .add(jLabel5)
                .add(shortcutkeyField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel6))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel3.setOpaque(false);

        hideButton.setText("Hide");

        quitButton.setText("Quit");

        saveSettingsButton.setText("Save Settings");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(saveSettingsButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 277, Short.MAX_VALUE)
                .add(hideButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(quitButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(quitButton)
                    .add(hideButton)
                    .add(saveSettingsButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loggingCheckBox.setSelected(true);
        loggingCheckBox.setText("Enable application logging (JavaPushMail.log)");
        loggingCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loggingCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(24, 24, 24)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, loggingCheckBox, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(18, 18, 18)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 192, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(6, 6, 6)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(7, 7, 7)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(loggingCheckBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JRadioButton darkThemeRadioBox;
    public javax.swing.JComboBox durationComboBox;
    public javax.swing.JRadioButton fallbackNotificationRadioButton;
    public javax.swing.JComboBox firstLineComboBox;
    public javax.swing.JRadioButton growlRadioButton;
    private javax.swing.JButton hideButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JCheckBox keyAltCheckBox;
    public javax.swing.JCheckBox keyCtrlCheckBox;
    public javax.swing.JRadioButton lightThemeRadioBox;
    public javax.swing.JCheckBox loggingCheckBox;
    public javax.swing.JRadioButton nOSDRadioButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton saveSettingsButton;
    public javax.swing.JComboBox secondLineComboBox;
    public javax.swing.JTextField shortcutkeyField;
    public javax.swing.JComboBox titleComboBox;
    // End of variables declaration//GEN-END:variables

    public JButton getQuitButton() {
        return quitButton;
    }
    public JButton getHideButton() {
        return hideButton;
    }
    public JButton getSaveSettingsButton() {
        return saveSettingsButton;
    }

    public JRadioButton getDarkThemeRadioBox() {
        return darkThemeRadioBox;
    }

    public JComboBox getDurationComboBox() {
        return durationComboBox;
    }

    public JRadioButton getFallbackNotificationRadioButton() {
        return fallbackNotificationRadioButton;
    }

    public JComboBox getFirstLineComboBox() {
        return firstLineComboBox;
    }

    public JRadioButton getGrowlRadioButton() {
        return growlRadioButton;
    }

    public JRadioButton getLightThemeRadioBox() {
        return lightThemeRadioBox;
    }

    public JCheckBox getLoggingCheckBox() {
        return loggingCheckBox;
    }

    public JRadioButton getnOSDRadioButton() {
        return nOSDRadioButton;
    }

    public JComboBox getSecondLineComboBox() {
        return secondLineComboBox;
    }

    public JTextField getShortcutkeyField() {
        return shortcutkeyField;
    }

    public JComboBox getTitleComboBox() {
        return titleComboBox;
    }
    
}
