/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JavaPushMailAccountSettingsPanel.java
 *
 * Created on Oct 23, 2011, 7:22:45 PM
 */
package com.mofirouz.javapushmail.app.ui;

import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author mo
 */
public class JavaPushMailAccountSettingsPanel extends javax.swing.JPanel {

    public final static String PASSWORD_FIELD = "*****";

    /** Creates new form JavaPushMailAccountSettingsPanel */
    public JavaPushMailAccountSettingsPanel() {
        initComponents();
        configTableUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        accountTable = new javax.swing.JTable();
        quitButton = new javax.swing.JButton();
        hideButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        newAccountButton = new javax.swing.JButton();
        connectButton = new javax.swing.JButton();

        accountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Port", "SSL?", "Username", "Password", "Enabled?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        accountTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        accountTable.setColumnSelectionAllowed(true);
        accountTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(accountTable);
        accountTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        quitButton.setText("Quit");

        hideButton.setText("Hide");

        jLabel1.setText(" Account List:");

        newAccountButton.setText("Add New Account");

        connectButton.setText("Connect");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(newAccountButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 128, Short.MAX_VALUE)
                        .add(connectButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(hideButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(quitButton))
                    .add(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 426, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newAccountButton)
                    .add(quitButton)
                    .add(hideButton)
                    .add(connectButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accountTable;
    private javax.swing.JButton connectButton;
    private javax.swing.JButton hideButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newAccountButton;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables

    public JButton getConnectButton() {
        return connectButton;
    }

    public JButton getHideButton() {
        return hideButton;
    }

    public JButton getNewAccountButton() {
        return newAccountButton;
    }

    public JButton getQuitButton() {
        return quitButton;
    }

    public JTable getAccountTable() {
        return accountTable;
    }

    private void configTableUI() {
        TableColumnModel colModel = accountTable.getColumnModel();
        colModel.getColumn(0).setPreferredWidth(175);
        colModel.getColumn(1).setPreferredWidth(175);
        colModel.getColumn(2).setPreferredWidth(50);
        colModel.getColumn(3).setPreferredWidth(50);
        colModel.getColumn(4).setPreferredWidth(100);
        colModel.getColumn(5).setPreferredWidth(100);
        colModel.getColumn(6).setPreferredWidth(80);

        for (int i = 0; i < accountTable.getColumnCount(); i++) {
            alignCenter(accountTable, i);
        }
    }
    
    private void alignCenter(JTable table, int column) {
        JTableHeader header = table.getTableHeader();
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer)header.getDefaultRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        table.getColumnModel().getColumn(column).setHeaderRenderer(renderer);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        table.getColumnModel().getColumn(column).setCellRenderer(centerRenderer);
    }
}
